num_hart_max = 8
stack_size_per_hart = 16384 # 16 * 1024
heap_size = 0x80000 # 512 * 1024
boot_dtb_max_size = 0x40000 # 256 KiB
boot_dtb_max_depth = 64
boot_dtb_max_nodes = 4096
boot_dtb_max_properties = 16384
boot_dtb_max_edits = 256
trusted_target = false
page_size = 4096
log_level = "INFO"
jump_address = 0x80200000
tlb_flush_limit = 16384 # page_size * 4

[[next_addr]]
start = 0x20000000
end = 0x24000000

[[next_addr]]
start = 0x80000000
end = 0x90000000
