[package]
name = "rustsbi-prototyper"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
machine = { package = "rustsbi-prototyper-machine", path = "../machine", default-features = false }
log = { version = "0.4", default-features = false }
rustsbi = { version = "0.4.1", features = [
    "machine",
], path = "../../library/rustsbi" }
sbi-spec = { version = "0.0.9", path = "../../library/sbi-spec" }
dtoolkit = { version = "0.3.0", default-features = false, features = ["write"] }
spin = "0.9.8"
sbi-testing = { version = "0.0.3", path = "../../library/sbi-testing", optional = true }

[lib]
test = false
bench = false
doctest = false

[[bin]]
name = "rustsbi-prototyper"
test = false
bench = false

[[bin]]
name = "rustsbi-prototyper-mtest"
path = "src/mtest/main.rs"
required-features = ["mtest"]
test = false
bench = false

[features]
default = []
nemu = []
hypervisor = ["machine/hypervisor"]
mtest = ["machine/mtest", "dep:sbi-testing"]
