//! Entry-point proc-macro for the RustSBI Prototyper firmware.

use proc_macro2::TokenStream;
use quote::quote;
use syn::ItemFn;

/// The firmware entry point: the marked function is the safe Rust policy
/// main, and everything before and after it is generated by this macro.
#[proc_macro_attribute]
pub fn entry(
    attribute: proc_macro::TokenStream,
    item: proc_macro::TokenStream,
) -> proc_macro::TokenStream {
    expand(attribute.into(), item.into()).into()
}

fn expand(attribute: TokenStream, item: TokenStream) -> TokenStream {
    if !attribute.is_empty() {
        return quote! { compile_error!("`entry` does not accept arguments"); };
    }
    let Ok(policy) = syn::parse2::<ItemFn>(item) else {
        return quote! { compile_error!("`entry` can be applied only to a function"); };
    };
    let name = &policy.sig.ident;

    quote! {
        #policy

        const _: () = {
            /// Connects the startup ceremony to the policy function.
            #[doc(hidden)]
            #[unsafe(export_name = "__rustsbi_prototyper_main")]
            extern "C" fn __rustsbi_prototyper_main(
                hart_id: usize,
                opaque: usize,
                nonstandard_a2: usize,
            ) {
                let entry: fn(usize, usize, usize) = #name;
                entry(hart_id, opaque, nonstandard_a2)
            }

            /// Applies the linker's relative relocations before Rust memory
            /// is initialized.
            ///
            /// # Safety
            ///
            /// Called exactly once by the elected boot hart from the `_start`
            /// ceremony, before BSS, stacks, or any Rust reference exist.
            #[doc(hidden)]
            #[unsafe(naked)]
            unsafe extern "C" fn relocation_update() {
                ::core::arch::naked_asm!(
                    include_str!("entry/relocation.S"),
                    R_RISCV_RELATIVE = const R_RISCV_RELATIVE,
                    START_ADDRESS = const crate::cfg::SBI_LINK_START_ADDRESS,
                )
            }

            const R_RISCV_RELATIVE: usize = 3;

            /// Architectural firmware entry point, referenced by
            /// `ENTRY(_start)` in the linker script generated by `build.rs`.
            ///
            /// # Safety
            ///
            /// The previous stage must enter with the register envelope of
            /// the selected boot protocol: `a0 = hart_id`, `a1 = opaque`,
            /// `a2 = nonstandard_a2`. Runs before relocation, BSS, and stacks
            /// exist, so the assembly may not touch Rust memory until those
            /// steps complete.
            #[doc(hidden)]
            #[unsafe(naked)]
            #[unsafe(link_section = ".text.entry")]
            #[unsafe(export_name = "_start")]
            unsafe extern "C" fn __rustsbi_prototyper_start() -> ! {
                ::core::arch::naked_asm!(
                    include_str!("entry/start.S"),
                    relocation_update = sym relocation_update,
                    locate_stack = sym crate::sbi::trap_stack::locate,
                    main = sym __rustsbi_prototyper_main,
                    hart_boot = sym crate::sbi::trap::boot::boot,
                )
            }
        };
    }
}

#[cfg(test)]
mod tests {
    use super::{TokenStream, expand};

    const POLICY_FN: &str = "fn main(a: usize, b: usize, c: usize) { loop {} }";

    fn normalized(tokens: TokenStream) -> String {
        tokens.to_string().split_whitespace().collect()
    }

    #[test]
    fn expands_policy_and_bridge() {
        let expanded = normalized(expand(TokenStream::new(), POLICY_FN.parse().unwrap()));
        assert!(expanded.contains("fnmain(a:usize,b:usize,c:usize){loop{}}"));
        assert_eq!(
            expanded
                .matches("export_name=\"__rustsbi_prototyper_main\"")
                .count(),
            1
        );
        assert!(expanded.contains("letentry:fn(usize,usize,usize)=main;"));
    }

    #[test]
    fn includes_startup_assembly() {
        let expanded = normalized(expand(TokenStream::new(), POLICY_FN.parse().unwrap()));
        assert_eq!(expanded.matches("export_name=\"_start\"").count(), 1);
        assert!(expanded.contains("include_str!(\"entry/start.S\")"));
        assert!(expanded.contains("include_str!(\"entry/relocation.S\")"));
    }

    #[test]
    fn bridge_forwards_arguments() {
        let expanded = normalized(expand(TokenStream::new(), POLICY_FN.parse().unwrap()));
        assert!(expanded.contains("entry(hart_id,opaque,nonstandard_a2)"));
    }

    #[test]
    fn rejects_arguments() {
        let result = expand("unexpected".parse().unwrap(), POLICY_FN.parse().unwrap());
        assert!(result.to_string().contains("compile_error"));
    }

    #[test]
    fn rejects_non_function_items() {
        let result = expand(TokenStream::new(), "struct S;".parse().unwrap());
        assert!(result.to_string().contains("compile_error"));
    }
}
