[package]
name = "riscv-cove-rt"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
riscv-cove = { version = "0.0.0", path = "../riscv-cove" }
sbi-spec = { version = "0.0.8", path = "../sbi-spec" }
sbi-rt = { version = "0.0.3", path = "../sbi-rt" }
