//! Link-time registry and single-case runner for privileged machine tests.
//!
//! This crate is linked only into the dedicated machine-test firmware. Each
//! firmware invocation selects exactly one registered test and terminates
//! afterward, so tests never need cleanup callbacks or shared-batch metadata.

#![no_std]
#![deny(unsafe_op_in_unsafe_fn)]
#![warn(missing_docs)]

use core::mem::{align_of, size_of};
use core::{slice, str};

/// Immutable entry collected in the dedicated linker section.
#[repr(C)]
pub struct Descriptor {
    name: *const u8,
    name_len: usize,
    test: extern "C" fn(),
}

// SAFETY: descriptors contain immutable string literals and function pointers.
// The registry is read-only after linking and one invocation runs one test.
unsafe impl Sync for Descriptor {}

impl Descriptor {
    /// Creates a descriptor from immutable compile-time metadata.
    pub const fn new(name: &'static str, test: extern "C" fn()) -> Self {
        Self {
            name: name.as_ptr(),
            name_len: name.len(),
            test,
        }
    }

    fn name(&self) -> Result<&'static str, RegistryError> {
        if self.name.is_null() || self.name_len == 0 {
            return Err(RegistryError::InvalidName);
        }
        // SAFETY: the declaration macro supplies a static `concat!` result and
        // preserves its exact pointer and length in the immutable descriptor.
        let bytes = unsafe { slice::from_raw_parts(self.name, self.name_len) };
        str::from_utf8(bytes).map_err(|_| RegistryError::InvalidName)
    }
}

/// Failure while validating the final image's machine-test registry.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RegistryError {
    /// Linker bounds or descriptor alignment are invalid.
    Bounds,
    /// The dedicated image contains no registered test.
    Empty,
    /// A descriptor name is empty, null, or not UTF-8.
    InvalidName,
    /// Two descriptors publish the same generated name.
    DuplicateName,
}

/// Validated machine-test registry retaining its machine-runtime owner.
pub struct Tests<Owner> {
    _owner: Owner,
    descriptors: &'static [Descriptor],
}

/// One test selected from a validated machine-test registry.
///
/// The function pointer remains private so upper firmware can invoke only the
/// exact case returned by [`Tests::select`].
pub struct SelectedTest<'registry> {
    descriptor: &'registry Descriptor,
}

impl SelectedTest<'_> {
    /// Returns the stable identifier generated by the declaration macro.
    pub fn name(&self) -> &'static str {
        self.descriptor
            .name()
            .expect("validated machine-test descriptor name")
    }

    /// Runs the selected test.
    ///
    /// Normal return means success. A panic is reported by the dedicated
    /// firmware panic path and cannot return through this method.
    pub fn run(self) {
        (self.descriptor.test)()
    }
}

impl<Owner> Tests<Owner> {
    /// Validates linker bounds and takes ownership of initialized machine state.
    ///
    /// # Safety
    ///
    /// `start..end` must be the immutable linker section containing only
    /// `Descriptor` objects emitted by the declaration macro in this image.
    pub unsafe fn from_linker_bounds(
        owner: Owner,
        start: usize,
        end: usize,
    ) -> Result<Self, RegistryError> {
        // SAFETY: the caller supplies the linker-owned descriptor envelope.
        let descriptors = unsafe { registry_from_bounds(start, end) }?;
        Ok(Self {
            _owner: owner,
            descriptors,
        })
    }

    /// Visits every registered name without exposing a function pointer.
    pub fn visit(&self, mut visitor: impl FnMut(&'static str)) {
        for descriptor in self.descriptors {
            visitor(
                descriptor
                    .name()
                    .expect("validated machine-test descriptor name"),
            );
        }
    }

    /// Selects exactly one named test without exposing raw registry authority.
    pub fn select(&self, name: &str) -> Option<SelectedTest<'_>> {
        self.descriptors
            .iter()
            .find(|descriptor| descriptor.name().is_ok_and(|candidate| candidate == name))
            .map(|descriptor| SelectedTest { descriptor })
    }
}

unsafe fn registry_from_bounds(
    start: usize,
    end: usize,
) -> Result<&'static [Descriptor], RegistryError> {
    let bytes = end.checked_sub(start).ok_or(RegistryError::Bounds)?;
    if !start.is_multiple_of(align_of::<Descriptor>())
        || !bytes.is_multiple_of(size_of::<Descriptor>())
    {
        return Err(RegistryError::Bounds);
    }
    let count = bytes / size_of::<Descriptor>();
    if count == 0 {
        return Err(RegistryError::Empty);
    }
    // SAFETY: the caller supplies the immutable linker envelope; alignment and
    // exact descriptor-size divisibility were checked above.
    let descriptors = unsafe { slice::from_raw_parts(start as *const Descriptor, count) };
    validate(descriptors)?;
    Ok(descriptors)
}

fn validate(descriptors: &[Descriptor]) -> Result<(), RegistryError> {
    for (index, descriptor) in descriptors.iter().enumerate() {
        let name = descriptor.name()?;
        for previous in &descriptors[..index] {
            if previous.name()? == name {
                return Err(RegistryError::DuplicateName);
            }
        }
    }
    Ok(())
}

const _: () = {
    assert!(size_of::<Descriptor>() == if size_of::<usize>() == 4 { 12 } else { 24 });
};

#[cfg(test)]
mod tests {
    extern crate std;

    use super::*;

    extern "C" fn pass() {}

    static REGISTRY: [Descriptor; 2] = [
        Descriptor::new("machine::a", pass),
        Descriptor::new("machine::b", pass),
    ];

    #[test]
    fn exact_selection_runs_only_the_named_case() {
        let tests = Tests {
            _owner: (),
            descriptors: &REGISTRY,
        };
        let selected = tests.select("machine::b").expect("registered test");
        assert_eq!(selected.name(), "machine::b");
        selected.run();
        assert!(tests.select("machine::missing").is_none());
    }

    #[test]
    fn duplicate_names_are_rejected_before_execution() {
        let duplicate = [Descriptor::new("same", pass), Descriptor::new("same", pass)];
        assert_eq!(validate(&duplicate), Err(RegistryError::DuplicateName));
    }
}
