[package]
name = "rustsbi-prototyper-machine"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
test = true
bench = false

[dependencies]
machine-macros = { package = "rustsbi-prototyper-machine-macros", path = "macros" }
machine-test = { package = "rustsbi-prototyper-machine-test", path = "../machine-test", optional = true }
dtoolkit = { version = "0.3.0", default-features = false, features = ["write"] }
spin = "0.9.8"
buddy_system_allocator = "0.11.0"
bitflags = "2"
sbi-spec = { path = "../../library/sbi-spec" }

[features]
default = []
mtest = ["dep:machine-test"]
hypervisor = []
