[alias]
xtask = "run --package xtask --release --"
arceboot = "xtask arceboot"
prototyper = "run --package cargo-prototyper --"
test-kernel = "xtask test"
bench-kernel = "xtask bench"

[env]
# Environment variables for ArceBoot
AX_CONFIG_PATH = { value = "arceboot/.axconfig.toml", relative = true }
