//! Entry-point proc-macro for the RustSBI Prototyper firmware.

use proc_macro2::TokenStream;
use quote::quote;
use syn::ItemFn;

/// The firmware entry point: the marked function is the safe Rust policy
/// main, and everything before and after it is generated by this macro.
#[proc_macro_attribute]
pub fn entry(
    attribute: proc_macro::TokenStream,
    item: proc_macro::TokenStream,
) -> proc_macro::TokenStream {
    expand(attribute.into(), item.into()).into()
}

fn expand(attribute: TokenStream, item: TokenStream) -> TokenStream {
    if !attribute.is_empty() {
        return quote! { compile_error!("`entry` does not accept arguments"); };
    }
    let Ok(policy) = syn::parse2::<ItemFn>(item) else {
        return quote! { compile_error!("`entry` can be applied only to a function"); };
    };
    let name = &policy.sig.ident;

    quote! {
        #policy

        const _: () = {
            /// Connects the startup ceremony to the policy function.
            #[doc(hidden)]
            #[unsafe(export_name = "__rustsbi_prototyper_main")]
            extern "C" fn __rustsbi_prototyper_main(_a0: usize, a1: usize, a2: usize) {
                // Boot register handoff from the previous stage:
                //   a0 = hart ID, a1 = device tree pointer (base RISC-V
                //   convention); a2 = DynamicInfo address (fw_dynamic
                //   extension, dynamic variant only).
                //
                // `_a0` keeps its slot but its value is unused: register
                // arguments bind by position, so removing the parameter
                // would shift `a1`/`a2`. In M-mode the hart ID is always
                // re-read from the mhartid CSR, and it is re-materialized
                // into `a0` when this firmware boots the next stage (see
                // `sbi::trap::boot`) — S-mode cannot read mhartid and
                // depends on receiving its hart ID this way.
                let entry: fn(crate::firmware::BootInfo) = #name;
                entry(crate::firmware::BootInfo::decode(a1, a2))
            }

            /// Applies the linker's relative relocations before Rust memory
            /// is initialized.
            ///
            /// # Safety
            ///
            /// Called exactly once by the elected boot hart from the `_start`
            /// ceremony, before BSS, stacks, or any Rust reference exist.
            #[doc(hidden)]
            #[unsafe(naked)]
            unsafe extern "C" fn relocation_update() {
                ::core::arch::naked_asm!(
                    include_str!("entry/relocation.S"),
                    R_RISCV_RELATIVE = const R_RISCV_RELATIVE,
                    START_ADDRESS = const crate::cfg::SBI_LINK_START_ADDRESS,
                )
            }

            const R_RISCV_RELATIVE: usize = 3;

            /// Architectural firmware entry point, referenced by
            /// `ENTRY(_start)` in the linker script generated by `build.rs`.
            ///
            /// # Safety
            ///
            /// The previous stage must enter with the register envelope of
            /// the selected boot protocol: `a0 = hart ID`, `a1 = device
            /// tree pointer` (base RISC-V convention), `a2 = DynamicInfo
            /// address` (fw_dynamic extension, dynamic variant only).
            /// Runs before relocation, BSS, and stacks exist, so the
            /// assembly may not touch Rust memory until those steps
            /// complete.
            #[doc(hidden)]
            #[unsafe(naked)]
            #[unsafe(link_section = ".text.entry")]
            #[unsafe(export_name = "_start")]
            unsafe extern "C" fn __rustsbi_prototyper_start() -> ! {
                ::core::arch::naked_asm!(
                    include_str!("entry/start.S"),
                    relocation_update = sym relocation_update,
                    locate_stack = sym crate::sbi::trap_stack::locate,
                    main = sym __rustsbi_prototyper_main,
                    hart_boot = sym crate::sbi::trap::boot::boot,
                )
            }

            /// SpacemiT K3 warm-boot entry, referenced by the cluster
            /// RVBADDR registers after platform initialization.
            #[doc(hidden)]
            #[unsafe(naked)]
            #[unsafe(link_section = ".text.warmboot")]
            #[unsafe(export_name = "_start_warm_k3")]
            unsafe extern "C" fn __rustsbi_prototyper_start_warm_k3() -> ! {
                ::core::arch::naked_asm!(
                    include_str!("entry/spacemit_k3.S"),
                    locate_stack = sym crate::sbi::trap_stack::locate,
                    main = sym __rustsbi_prototyper_main,
                    hart_boot = sym crate::sbi::trap::boot::boot,
                )
            }
        };
    }
}

#[cfg(test)]
mod tests {
    use super::{TokenStream, expand};

    const POLICY_FN: &str = "fn main(boot: crate::firmware::BootInfo) { loop {} }";

    fn normalized(tokens: TokenStream) -> String {
        tokens.to_string().split_whitespace().collect()
    }

    #[test]
    fn expands_policy_and_bridge() {
        let expanded = normalized(expand(TokenStream::new(), POLICY_FN.parse().unwrap()));
        assert!(expanded.contains("fnmain(boot:crate::firmware::BootInfo){loop{}}"));
        assert_eq!(
            expanded
                .matches("export_name=\"__rustsbi_prototyper_main\"")
                .count(),
            1
        );
        assert!(expanded.contains("letentry:fn(crate::firmware::BootInfo)=main;"));
    }

    #[test]
    fn includes_startup_assembly() {
        let expanded = normalized(expand(TokenStream::new(), POLICY_FN.parse().unwrap()));
        assert_eq!(expanded.matches("export_name=\"_start\"").count(), 1);
        assert_eq!(
            expanded.matches("export_name=\"_start_warm_k3\"").count(),
            1
        );
        assert!(expanded.contains("link_section=\".text.entry\""));
        assert!(expanded.contains("link_section=\".text.warmboot\""));
        assert!(expanded.contains("include_str!(\"entry/start.S\")"));
        assert!(expanded.contains("include_str!(\"entry/spacemit_k3.S\")"));
        assert!(expanded.contains("include_str!(\"entry/relocation.S\")"));
    }

    #[test]
    fn bridge_forwards_arguments() {
        let expanded = normalized(expand(TokenStream::new(), POLICY_FN.parse().unwrap()));
        assert!(expanded.contains("entry(crate::firmware::BootInfo::decode(a1,a2))"));
    }

    #[test]
    fn rejects_arguments() {
        let result = expand("unexpected".parse().unwrap(), POLICY_FN.parse().unwrap());
        assert!(result.to_string().contains("compile_error"));
    }

    #[test]
    fn rejects_non_function_items() {
        let result = expand(TokenStream::new(), "struct S;".parse().unwrap());
        assert!(result.to_string().contains("compile_error"));
    }
}
